import UIComponent from './UIComponent.js';

export default class ToDoWidget extends UIComponent {
  constructor(config = {}) { super({ title: 'Раундовые задачи', id: config.id || `todo-${Date.now()}` }); this.tasks = []; this.onRemove = config.onRemove; }
  render() { const card = super.render(); card.classList.add('todo-widget'); card.innerHTML = '<div class="panel-heading"><div><p class="eyebrow">WARMUP / TODO</p><h2>Задачи перед матчем</h2></div><button class="widget-remove" type="button" aria-label="Удалить виджет">×</button></div><form class="todo-form"><label class="sr-only" for="todo-input">Новая задача</label><input id="todo-input" maxlength="80" placeholder="Например: проверить гранаты" required /><button type="submit">Добавить</button></form><ul class="todo-list"></ul>'; this.input = card.querySelector('input'); this.list = card.querySelector('.todo-list'); this.on(card.querySelector('form'), 'submit', event => { event.preventDefault(); this.addTask(this.input.value); this.input.value = ''; this.input.focus(); }); this.on(card.querySelector('.widget-remove'), 'click', () => { this.destroy(); this.onRemove?.(this.id); }); this.on(this.list, 'change', event => this.toggleTask(event.target.dataset.task)); this.on(this.list, 'click', event => { if (event.target.dataset.remove) this.removeTask(event.target.dataset.remove); }); this.renderTasks(); return card; }
  addTask(text) { const value = text.trim(); if (!value) return; this.tasks.push({ id: crypto.randomUUID(), text: value, done: false }); this.renderTasks(); }
  toggleTask(id) { const task = this.tasks.find(item => item.id === id); if (task) task.done = !task.done; this.renderTasks(); }
  removeTask(id) { this.tasks = this.tasks.filter(task => task.id !== id); this.renderTasks(); }
  renderTasks() { if (!this.list) return; this.list.replaceChildren(...this.tasks.map(task => { const item = document.createElement('li'); item.className = task.done ? 'done' : ''; const label = document.createElement('label'); const checkbox = document.createElement('input'); checkbox.type = 'checkbox'; checkbox.dataset.task = task.id; checkbox.checked = task.done; const text = document.createElement('span'); text.textContent = task.text; const remove = document.createElement('button'); remove.type = 'button'; remove.className = 'todo-remove'; remove.textContent = '×'; remove.dataset.remove = task.id; remove.setAttribute('aria-label', `Удалить задачу: ${task.text}`); label.append(checkbox, text); item.append(label, remove); return item; })); }
}
